#!/usr/bin/env python3.4
import os
import sys
import getopt
import hmac
import hashlib
import urllib.request
import urllib.parse
import json
import getpass
import subprocess
import ntpath

versionBLIH = 1.7
versionBLIHTEK = 0.6

class blih:
	def __init__(self, baseurl='https://blih.epitech.eu/', user=None, token=None, verbose=False, user_agent='blih-' + str(versionBLIH) + '-linux'):
		self._baseurl = baseurl
		if token:
			self._token = token
		else:
			self.token_calc()
		if user == None:
			self._user = getpass.getuser()
		else:
			self._user = user
		self._verbose = verbose
		self._useragent = user_agent

	def token_get(self):
		return self._token

	def token_set(self, token):
		self._token = token

	token = property(token_get, token_set)

	def token_calc(self):
		self._token = bytes(hashlib.sha512(bytes(getpass.getpass(), 'utf8')).hexdigest(), 'utf8')

	def sign_data(self, data=None):
		signature = hmac.new(self._token, msg=bytes(self._user, 'utf8'), digestmod=hashlib.sha512)
		if data:
			signature.update(bytes(json.dumps(data, sort_keys=True, indent=4, separators=(',', ': ')), 'utf8'))

		signed_data = {'user' : self._user, 'signature' : signature.hexdigest()}
		if data != None:
			signed_data['data'] = data

		return signed_data

	def request(self, resource, method='GET', content_type='application/json', data=None, url=None):
		signed_data = self.sign_data(data)

		if url:
			req = urllib.request.Request(url=url, method=method, data=bytes(json.dumps(signed_data), 'utf8'))
		else:
			req = urllib.request.Request(url=self._baseurl + resource, method=method, data=bytes(json.dumps(signed_data), 'utf8'))
		req.add_header('Content-Type', content_type)
		req.add_header('User-Agent', self._useragent)

		try:
			f = urllib.request.urlopen(req)
		except urllib.error.HTTPError as e:
			print (setcolor("red") + 'HTTP Error ' + str(e.code) + setcolor(""))
			data = json.loads(e.read().decode('utf8'))
			print (setcolor("red") + "Error message" + setcolor("") + " : '" + data['error'] + "'")
			sys.exit(1)

		if f.status == 200:
			try:
				data = json.loads(f.read().decode('utf8'))
			except:
				print (setcolor("red") + "Can't decode data, aborting" + setcolor(""))
				sys.exit(1)
			return (f.status, f.reason, f.info(), data)

		print (setcolor("red") + 'Unknown error' + setcolor(""))
		sys.exit(1)

	def repo_create(self, name, type='git', description=None):
		data = {'name' : name, 'type' : type}
		if description:
			data['description'] = description
		status, reason, headers, data = self.request('/repositories', method='POST', data=data)
		print (setcolor("green") + data['message'] + setcolor(""))

	def repo_list(self):
		status, reason, headers, data = self.request('/repositories', method='GET')
		result = [];
		for i in data['repositories']:
			result.append(i)
		result.sort()
		for i in result:
			print (setcolor("green") + i + setcolor(""))

	def repo_delete(self, name):
		status, reason, headers, data = self.request('/repository/' + name, method='DELETE')
		print (setcolor("green") + data['message'] + setcolor(""))

	def repo_info(self, name):
		status, reason, headers, data = self.request('/repository/' + name, method='GET')
		print (setcolor("green") + data['message'] + setcolor(""))

	def repo_setacl(self, name, acluser, acl):
		data = {'user' : acluser, 'acl' : acl}
		status, reason, headers, data = self.request('/repository/' + name + '/acls', method='POST', data=data)
		print (setcolor("green") + data['message'] + setcolor(""))

	def repo_getacl(self, name):
		status, reason, headers, data = self.request('/repository/' + name + '/acls', method='GET')
		for i in data.keys():
			print (setcolor("green") + i + setcolor("") + '\t' + setcolor("blue") + data[i] + setcolor(""))

	def sshkey_upload(self, keyfile):
		try:
			f = open(keyfile, 'r')
		except (PermissionError, FileNotFoundError):
			print (setcolor("red") + "Can't open file" + setcolor("") + " : " + keyfile)
			return
		key = urllib.parse.quote(f.read().strip('\n'))
		f.close()
		data = {'sshkey' : key}
		status, reason, headers, data = self.request('/sshkeys', method='POST', data=data)
		print (setcolor("green") + data['message'] + setcolor(""))

	def sshkey_delete(self, sshkey):
		status, reason, headers, data = self.request('/sshkey/' + sshkey, method='DELETE')
		print (setcolor("green") + data['message'] + setcolor(""))

	def sshkey_list(self):
		status, reason, headers, data = self.request('/sshkeys', method='GET')
		for i in data.keys():
			print (setcolor("green") + i + setcolor("") + '\n' + data[i] + '\n')

	def whoami(self):
		status, reason, headers, data = self.request('/whoami', method='GET')
		print (setcolor("green") + data['message'] + setcolor(""))

class blihtek:
	def repo_clone(user, login, repo, folder):
		command = "git clone " + user + "@git.epitech.eu:/" + login + "/" + repo + " " + folder + "/" + repo
		try:
			res = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
		except Exception:
			print (setcolor("red") + "Error with repository" + setcolor(""))
			sys.exit(0)
		print (setcolor("green") + "Repository cloned" + setcolor(""))

	def repo_link(user, login, repo, folder):
		if os.path.isdir(folder) == False:
			print (setcolor("red") + "Folder does not exist" + setcolor(""))
			sys.exit(0)
		pwd_save = os.getenv('PWD')
		command = "cd " + folder + "&& git init && git remote add origin " + user + "@git.epitech.eu:/" + login + "/" + repo + "&& cd " + pwd_save
		try:
			res = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
		except Exception:
			print (setcolor("red") + "Error with repository" + setcolor(""))
			sys.exit(0)
		print (setcolor("green") + "Repository linked" + setcolor(""))

	def conf_crypt():
		token = bytes(hashlib.sha512(bytes(getpass.getpass(setcolor("green") + 'Your password :' + setcolor("")), 'utf8')).hexdigest(), 'utf8')
		print(token.decode("utf-8"))

	def conf_disp(variable):
		if variable == "login":
			if os.getenv("EPITECH_LOGIN") != None:
				print (setcolor("green") + "EPITECH_LOGIN" + setcolor("") + "\n" + os.getenv("EPITECH_LOGIN"))
			else:
				print (setcolor("red") + "EPITECH_LOGIN is not set" + setcolor(""))
		elif variable == "token":
			if os.getenv("EPITECH_TOKEN") != None:
				print (setcolor("green") + "EPITECH_TOKEN" + setcolor("") + "\n" + os.getenv("EPITECH_TOKEN"))
			else:
				print (setcolor("red") + "EPITECH_TOKEN is not set" + setcolor(""))
		elif variable == "folder":
			if os.getenv("EPITECH_FOLDER") != None:
				print (setcolor("green") + "EPITECH_FOLDER" + setcolor("") + "\n" + os.getenv("EPITECH_FOLDER"))
			else:
				print (setcolor("red") + "EPITECH_FOLDER is not set" + setcolor(""))
		else:
			usage("config")

def repository(args, baseurl, user, token, verbose, folder, user_agent):
	if len(args) == 0:
		usage("repo")
	if args[0] == 'new':
		if len(args) != 2:
			usage("repo")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_create(args[1])
		handle.repo_setacl(args[1], 'ramassage-tek', 'r')
		blihtek.repo_clone(user, user, args[1], folder)
	elif args[0] == 'create':
		if len(args) != 2:
			usage("repo")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_create(args[1])
		handle.repo_setacl(args[1], 'ramassage-tek', 'r')
	elif args[0] == 'clone':
		if len(args) == 2:
			blihtek.repo_clone(user, user, args[1], folder)
		elif len(args) == 3:
			blihtek.repo_clone(user, args[1], args[2], folder)
		else:
			usage("repo")
	elif args[0] == 'link':
		if len(args) == 2:
			blihtek.repo_link(user, user, args[1], folder)
		elif len(args) == 3:
			blihtek.repo_link(user, args[1], args[2], folder)
		else:
			usage("repo")
	elif args[0] == 'list':
		if len(args) != 1:
			usage("repo")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_list()
	elif args[0] == 'info':
		if len(args) != 2:
			usage("repo")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_info(args[1])
	elif args[0] == 'delete':
		if len(args) != 2:
			usage("repo")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_delete(args[1])
	elif args[0] == 'setacl':
		if len(args) != 4 and len(args) != 3:
			usage("repo")
		if len(args) == 3:
			acl = ''
		else:
			acl = args[3]
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_setacl(args[1], args[2], acl)
	elif args[0] == 'getacl':
		if len(args) != 2:
			usage("repo")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.repo_getacl(args[1])
	else:
		usage("repo")

def sshkey(args, baseurl, user, token, verbose, folder, user_agent):
	if len(args) == 0:
		usage("ssh")
	if args[0] == 'list':
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.sshkey_list()
	elif args[0] == 'upload':
		key = None
		if len(args) == 1:
			key = os.getenv('HOME') + '/.ssh/id_rsa.pub'
		elif len(args) == 2:
			key = args[1]
		else:
			usage("ssh")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.sshkey_upload(key)
	elif args[0] == 'delete':
		if len(args) != 2:
			usage("ssh")
		handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
		handle.sshkey_delete(args[1])
	else:
		usage("ssh")

def whoami(args, baseurl, user, token, verbose, folder, user_agent):
	handle = blih(baseurl=baseurl, user=user, token=token, verbose=verbose, user_agent=user_agent)
	handle.whoami()

def config(args, baseurl, user, token, verbose, folder, user_agent):
	if len(args) == 0:
		usage("config")
	if args[0] == 'crypt':
		blihtek.conf_crypt()
	elif args[0] == 'disp':
		if len(args) == 1:
			blihtek.conf_disp("login")
			blihtek.conf_disp("token")
			blihtek.conf_disp("folder")
		elif len(args) == 2:
			blihtek.conf_disp(args[1])
		else:
			usage("config")
	else:
		usage("config")

def version():
	lastVersion = urllib.request.urlopen('https://raw.githubusercontent.com/hug33k/blihtek/master/.version').read().decode('utf-8').replace('\n', '')
	if lastVersion <= str(versionBLIHTEK):
		isUpdate = False
	else:
		isUpdate = True
	print (setcolor("blue") + 'Versions\n')
	print ('blih\t' + setcolor("green") + str(versionBLIH))
	if isUpdate == False:
		print (setcolor("blue") + 'blihtek\t' + setcolor("green") + str(versionBLIHTEK) + setcolor(""))
	else:
		print (setcolor("blue") + 'blihtek\t' + setcolor("red") + str(versionBLIHTEK))
		print (setcolor("red") + 'An update is available ' + setcolor("green") + '(' + lastVersion + ')' + setcolor(""))
	sys.exit(0)

def setcolor(color):
	if colors == True:
		if color == "red":
			return '\033[1;31m'
		elif color == "blue":
			return '\033[1;34m'
		elif color == "green":
			return '\033[1;32m'
		else:
			return '\033[0m'
	else:
		return ""

def usage(mode):
	name = ntpath.basename(sys.argv[0])
	if mode == "repo":
		print (setcolor("red") + 'Usage: ' + name + ' [options] repository command ...')
		print (setcolor(""))
		print ('Commands :')
		print ('\tnew ' + setcolor("blue") + 'repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Create and clone the repository ' + setcolor("blue") + 'repo' + setcolor(""))
		print ('\tcreate ' + setcolor("blue") + 'repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Create the repository ' + setcolor("blue") + 'repo' + setcolor(""))
		print ('\tclone ' + setcolor("blue") + 'repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Clone the repository ' + setcolor("blue") + 'repo' + setcolor(""))
		print ('\tclone ' + setcolor("blue") + 'user repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Clone the repository ' + setcolor("blue") + 'repo' + setcolor("green") + ' of ' + setcolor("blue") + 'user' + setcolor(""))
		print ('\tlink ' + setcolor("blue") + 'repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Link the current directory with ' + setcolor("blue") + 'repo' + setcolor(""))
		print ('\tlink ' + setcolor("blue") + 'user repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Link the current directory with ' + setcolor("blue") + 'repo' + setcolor("green") + ' of ' + setcolor("blue") + 'user' + setcolor(""))
		print ('\tinfo ' + setcolor("blue") + 'repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Get the repository ' + setcolor("blue") + 'info' + setcolor("green") + ' metadata' + setcolor(""))
		print ('\tgetacl ' + setcolor("blue") + 'repo' + setcolor("") + '\t\t\t--' + setcolor("green") + ' Get the acls set for the repository ' + setcolor("blue") + 'repo' + setcolor(""))
		print ('\tlist\t\t\t\t--' + setcolor("green") + ' List the repositories created' + setcolor(""))
		print ('\tsetacl ' + setcolor("blue") + 'repo user acl' + setcolor("") + '\t\t--' + setcolor("green") + ' Set (or remove) an acl for ' + setcolor("blue") + 'user' + setcolor("green") + ' on ' + setcolor("blue") + 'repo' + setcolor(""))
		print ('\t\t\t\t\tACL format:')
		print ('\t\t\t\t\t' + setcolor("blue") + 'r' + setcolor("") + ' for ' + setcolor("green") + 'read' + setcolor(""))
		print ('\t\t\t\t\t' + setcolor("blue") + 'w' + setcolor("") + ' for ' + setcolor("green") + 'write' + setcolor(""))
		print ('\t\t\t\t\t' + setcolor("blue") + 'a' + setcolor("") + ' for ' + setcolor("green") + 'admin' + setcolor(""))
	elif mode == "ssh":
		print (setcolor("red") + 'Usage: ' + name + ' [options] sshkey command ...')
		print (setcolor(""))
		print ('Commands :')
		print ('\tupload ' + setcolor("blue") + 'file' + setcolor("") + '\t\t\t-- ' + setcolor("green") + 'Upload a new ssh-key' + setcolor(""))
		print ('\tlist\t\t\t\t-- ' + setcolor("green") + 'List the ssh-keys' + setcolor(""))
		print ('\tdelete ' + setcolor("blue") + 'sshkey' + setcolor("") + '\t\t\t-- ' + setcolor("green") + 'Delete the sshkey with comment ' + setcolor("blue") + 'sshkey' + setcolor(""))
	elif mode == "config":
		print (setcolor("red") + 'Usage: ' + name + ' [options] config command ...')
		print (setcolor(""))
		print ('Commands :')
		print ('\tcrypt ' + '\t\t\t\t-- ' + setcolor("green") + 'Crypt your password in SHA512 for ' + setcolor("blue") + 'EPITECH_TOKEN' + setcolor(""))
		print ('\tdisp ' + '\t\t\t\t-- ' + setcolor("green") + 'Display all the values of blihtek variables' + setcolor(""))
		print ('\tdisp ' + setcolor("blue") + 'variable' + setcolor("") + '\t\t\t-- ' + setcolor("green") + 'Display the value of blihtek ' + setcolor("blue") + 'variable' + setcolor(""))
		print ('\t\t\t\t\tVariables:')
		print ('\t\t\t\t\t' + setcolor("blue") + 'login' + setcolor("") + '  for ' + setcolor("green") + 'EPITECH_LOGIN' + setcolor(""))
		print ('\t\t\t\t\t' + setcolor("blue") + 'token' + setcolor("") + '  for ' + setcolor("green") + 'EPITECH_TOKEN' + setcolor(""))
		print ('\t\t\t\t\t' + setcolor("blue") + 'folder' + setcolor("") + ' for ' + setcolor("green") + 'EPITECH_FOLDER' + setcolor(""))
	else:
		print (setcolor("red") + 'Usage: ' + name + ' [options] command ...')
		print (setcolor(""))
		print ('Global Options :')
		print ('\t-u ' + setcolor("blue") + 'user' + setcolor("") + ' | --user=' + setcolor("blue") + 'user' + setcolor("") + '\t\t-- ' + setcolor("green") + 'Run as ' + setcolor("blue") + 'user' + setcolor(""))
		print ('\t-f ' + setcolor("blue") + 'folder' + setcolor("") + ' | --folder=' + setcolor("blue") + 'folder' + setcolor("") + '\t-- ' + setcolor("green") + 'Execute in ' + setcolor("blue") + 'folder' + setcolor(""))
		print ('\t-v | --verbose\t\t\t-- ' + setcolor("green") + 'Verbose' + setcolor(""))
		print ('\t-c | --nocolor\t\t\t-- ' + setcolor("green") + 'Remove the colors' + setcolor(""))
		print ('\t-b ' + setcolor("blue") + 'url' + setcolor("") + ' | --baseurl=' + setcolor("blue") + 'url' + setcolor("") + '\t\t-- ' + setcolor("green") + 'Base URL for BLIH' + setcolor(""))
		print ('\t-t ' + setcolor("blue") + 'token' + setcolor("") + ' | --token ' + setcolor("blue") + 'token' + setcolor("") + '\t-- ' + setcolor("green") + 'Specify token in the cmdline' + setcolor(""))
		print ('\t-V | --version\t\t\t-- ' + setcolor("green") + 'Version' + setcolor(""))
		print ()
		print ('Commands :')
		print ('\trepository\t\t\t-- ' + setcolor("green") + 'Repository management' + setcolor(""))
		print ('\tsshkey\t\t\t\t-- ' + setcolor("green") + 'SSH-KEYS management' + setcolor(""))
		print ('\twhoami\t\t\t\t-- ' + setcolor("green") + 'Print who you are' + setcolor(""))
		print ('\tconfig\t\t\t\t-- ' + setcolor("green") + 'Modify blihtek configuration' + setcolor(""))
		print ()
		print ('Environment variables :')
		print ('\tEPITECH_LOGIN\t\t\t-- ' + setcolor("green") + 'Your login' + setcolor(""))
		print ('\tEPITECH_TOKEN\t\t\t-- ' + setcolor("green") + 'Your UNIX password in SHA512' + setcolor(""))
		print ('\tEPITECH_FOLDER\t\t\t-- ' + setcolor("green") + 'Your work folder' + setcolor(""))
	print (setcolor(""))
	sys.exit(1)

if __name__ == "__main__":
	try:
		opts, args = getopt.getopt(sys.argv[1:], 'hf:cvu:b:t:VU:', ['help', 'folder=', 'nocolor', 'verbose', 'user=', 'baseurl=', 'token=', 'version', 'useragent='])
	except getopt.GetoptError as e:
		print (e)
		usage()

	verbose = False
	user = None
	baseurl = 'https://blih.epitech.eu/'
	token = None
	user_agent = 'blih-' + str(versionBLIH)
	folder = os.getenv('PWD')
	global colors
	colors = True

	for o, a in opts:
		if o in ('-h', '--help'):
			usage("")
		elif o in ('-f', '--folder'):
			folder = a
		elif o in ('-v', '--verbose'):
			verbose = True
		elif o in ('-c', '--nocolor'):
			colors = False
		elif o in ('-u', '--user'):
			print ("user:" + a)
			user = a
		elif o in ('-b', '--baseurl'):
			baseurl = a
		elif o in ('-t', '--token'):
			token = bytes(a, 'utf8')
		elif o in ('-V', '--version'):
			version()
		elif o in ('-U', '--useragent'):
			user_agent = a
		else:
			usage("")

	if len(args) == 0:
		usage("")

	if user == None:
		if os.getenv("EPITECH_LOGIN") != None and os.getenv("EPITECH_LOGIN") != "":
			user = os.getenv("EPITECH_LOGIN")
		else:
			user = getpass.getuser()
	if token == None:
		if args[0] == 'config' and args[1] == 'crypt':
			token = ""
		if os.getenv("EPITECH_TOKEN") != None and os.getenv("EPITECH_TOKEN") != "":
			token = bytes(os.getenv("EPITECH_TOKEN"), 'utf8')
		else:
			token = bytes(hashlib.sha512(bytes(getpass.getpass(setcolor("green") + 'Your password :' + setcolor("")), 'utf8')).hexdigest(), 'utf8')

	if args[0] == 'repository':
		repository(args[1:], baseurl, user, token, verbose, folder, user_agent)
	elif args[0] == 'sshkey':
		sshkey(args[1:], baseurl, user, token, verbose, folder, user_agent)
	elif args[0] == 'whoami':
		whoami(args[1:], baseurl, user, token, verbose, folder, user_agent)
	elif args[0] == 'config':
		config(args[1:], baseurl, user, token, verbose, folder, user_agent)
	else:
		usage("")
